imgfix/urls.py
from django.urls import path
from .views import PersonCreateView,PersonListView

app_name = 'imgfix'
urlpatterns = [
    path('', PersonListView.as_view()),
    path('create/', PersonCreateView.as_view())
]    

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/[question_id]/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/[question_id]/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/[question_id]/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

upload_form/urls.py
from django.urls import path
from upload_form import views

app_name = 'upload_form'
urlpatterns = [
    #url(r'^$', views.form, name = 'form'),
    #url(r'^complete/', views.complete, name = 'complete'),
    path('', views.form, name = 'form'),
    path('complete/', views.complete, name = 'complete'),
]

imgfix/models.py
from django.db import models

# Create your models here.
class Person(models.Model):

    name = models.CharField(max_length=255)
    age = models.IntegerField(default=25)
    

polls/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200) # テキスト数を定義するフィールド
    pub_date = models.DateTimeField('date published') # 日時フィールド
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):# 最も新しい投稿にTureを返す
        # 昨日以降に作成された投稿にTureを返す
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #リレーションシップ定義 
    choice_text = models.CharField(max_length=200) 
    votes = models.IntegerField(default=0) # 数字を定義するフィールド
    def __str__(self):
        return self.choice_text

upload_form/models.py
from django.db import models
from datetime import datetime

class FileNameModel(models.Model):
    file_name = models.CharField(max_length = 50)
    upload_time = models.DateTimeField(default = datetime.now)

imgfix/forms.py
from django import forms
from .models import Person


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ("name", "age")
    

imgfix/views.py
from django.views.generic import CreateView, ListView
from .models import Person
from .forms import PersonForm


class PersonCreateView(CreateView):
    model = Person
    form_class = PersonForm
    template_name = "imgfix/form.html"
    success_url = "/imgfix"  # 成功時にリダイレクトするURL    
    
    
class PersonListView(ListView):
    model = Person
    template_name = "imgfix/list.html"

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

upload_form/views.py
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.conf import settings
from upload_form.models import FileNameModel
import sys, os

UPLOADE_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/files/'

def form(request):
    if request.method != 'POST':
        return render(request, 'upload_form/form.html')

    file = request.FILES['file']
    path = os.path.join(UPLOADE_DIR, file.name)
    destination = open(path, 'wb')

    for chunk in file.chunks():
        destination.write(chunk)

    insert_data = FileNameModel(file_name = file.name)
    insert_data.save()

    return redirect('upload_form:complete')

def complete(request):
    return render(request, 'upload_form/complete.html')

imgfix/templates/imgfix/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Person</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

imgfix/templates/imgfix/form.html
{% extends "imgfix/base.html" %}

{% block title %}アップローダサンプル{% endblock title %}
{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="送信"/>
</form>
{% endblock content %}

imgfix/templates/imgfix/list.html
{% extends "imgfix/base.html" %}

{% block content %}

    <h1>Person List</h1>
    <a href="/imgfix/create">create person</a>
    <ul>
    {% for person in object_list %}
        <li>名前：{{ person.name }}、年齢：{{ person.age }}</li>
    {% endfor %}
    </ul>

{% endblock %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <!--<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>-->
	<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/vote.html
{{question}}

templates/imgfix/img_view.html
<head>
</head>
<body>
<h1>こんにちは</h1>
</body>

upload_form/templates/upload_form/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="content">
        <title>ファイルアップローダ</title>
    </head>
    <body>
        {% block content %}
            {{ content }}
        {% endblock %}
    </body>
</html>

upload_form/templates/upload_form/complete.html
{% extends "upload_form/base.html" %}

{% block title %}アップロード完了{% endblock title %}
{% block content %}
    <div align="center">
        <h1 align="center">アップロード完了</h1>
        <a href="{% url 'upload_form:form' %}"><button>戻る</button></a>
    </div>
{% endblock content %}

upload_form/templates/upload_form/form.html
{% extends "upload_form/base.html" %}

{% block title %}アップローダサンプル{% endblock title %}
{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file">
        <input type="submit" value="アップロード">
    </form>
{% endblock content %}